alter table Advert 
    drop constraint FK74A35BF4F310D740;

alter table link_category_advert
    drop constraint FKA7C387F06613C4A3;

alter table link_category_advert
    drop constraint FKA7C387F07F2F2556;

drop table AdUser if exists;
drop table Advert if exists;
drop table Category if exists;
drop table Message if exists;
drop table link_category_advert if exists;

create table AdUser (
    id bigint generated by default as identity (start with 1),
    name varchar(255),
    password varchar(255),
    primary key (id),
    unique (name)
);

create table Advert (
    id bigint generated by default as identity (start with 1),
    message varchar(255),
    title varchar(255),
    aduser bigint,
    primary key (id)
);

create table Category (
    id bigint generated by default as identity (start with 1),
    title varchar(255),
    primary key (id),
    unique (title)
);

create table Message (
    id integer generated by default as identity (start with 1),
    messageText varchar(255),
    primary key (id)
);

create table link_category_advert (
    categories_id bigint not null,
    adverts_id bigint not null,
    primary key (categories_id, adverts_id)
);

alter table Advert
    add constraint FK74A35BF4F310D740
    foreign key (aduser)
    references AdUser;

alter table link_category_advert
    add constraint FKA7C387F06613C4A3
    foreign key (categories_id)
    references Category;

alter table link_category_advert
    add constraint FKA7C387F07F2F2556
    foreign key (adverts_id)
    references Advert;
